FROM golang:1.26.0 AS builder

FROM chainguard/wolfi-base@sha256:3490ac41510e17846b30c9ebfc4a323dfdecbd9a35e7b0e4e745a8f496a18f25
ENV GOLANG_VERSION=1.26.0
ENV GOTOOLCHAIN=local
ENV GOPATH=/go
ENV PATH="${GOPATH}/bin:/usr/local/go/bin:${PATH}"
COPY --from=builder /go $GOPATH
COPY --from=builder /usr/local/go /usr/local/go
