FROM eclipse-temurin:21.0.4_7-jre as builder

FROM chainguard/wolfi-base@sha256:3490ac41510e17846b30c9ebfc4a323dfdecbd9a35e7b0e4e745a8f496a18f25
ENV JAVA_HOME=/usr/lib/jvm/openjdk
ENV PATH="${JAVA_HOME}/bin:${PATH}"
ENV LANG=en_US.UTF-8
COPY --from=builder /opt/java/openjdk $JAVA_HOME
